author: p000ison
database: false
description: Allows you to enter a DreamWorld/NightMareWorld.
main: me.p000ison.dreamz.DreamZ
name: DreamZ
startup: postworld
url: http://dev.bukkit.org/server-mods/DreamZ/
version: '0.1.6'
commands:
  dreamz:
    description: Basic Command.
    usage: /<command>
permissions:
  dreamz.enter:
    description: Allows you to enter a dream.
  dreamz.command.reload:
    description: Allows you to use the command /dreamz reload to reload the config.
  dreamz.command.dwbed:
    description: Allows you to use the command /dreamz dwbed to set the bed in DreamWorld to escape.
  dreamz.command.nmbed:
    description: Allows you to use the command /dreamz dwbed to set the bed in NightMare to escape.
  dreamz.command.wakeup:
    description: Allows you to use the command /dreamz wakeup to escape from the dreamworld.
  dreamz.command.sleep:
    description: Allows you to use the command /dreamz sleep to enter the dream.
  dreamz.escape.damage:
    description: Allows you to escape throw damage cause.
  dreamz.fly:
    description: Allows you to fly.
  dreamz.join.noteleportback:
    description: If you have this permission you wont get teleported back, when you enter this world after a reconnect when the timer already has stopped.
    default: false
  dreamz.admin.*:
    description: Default Admin Permissions.
    default: op
    children:
      dreamz.enter: true
      dreamz.command.reload: true
      dreamz.command.dwbed: true
      dreamz.command.nmbed: true
      dreamz.command.wakeup: true
      dreamz.command.sleep: true
      dreamz.escape.damage: true
      dreamz.fly: true
  dreamz.user.*:
    description: Default Player Permissions.
    default: true
    children:
      dreamz.enter: true
      dreamz.escape.damage: true
      dreamz.fly: true